package dotenv

import (
	"strings"
	"testing"
)

func TestFormat_BasicOutput(t *testing.T) {
	secrets := map[string]string{"FOO": "bar"}
	out := Format(secrets, FormatOptions{})
	if !strings.Contains(out, "FOO=bar") {
		t.Errorf("expected FOO=bar in output, got: %s", out)
	}
}

func TestFormat_SortedKeys(t *testing.T) {
	secrets := map[string]string{"Z_KEY": "1", "A_KEY": "2", "M_KEY": "3"}
	out := Format(secrets, FormatOptions{SortKeys: true})
	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) != 3 {
		t.Fatalf("expected 3 lines, got %d", len(lines))
	}
	if !strings.HasPrefix(lines[0], "A_KEY") {
		t.Errorf("expected first line to be A_KEY, got %s", lines[0])
	}
	if !strings.HasPrefix(lines[2], "Z_KEY") {
		t.Errorf("expected last line to be Z_KEY, got %s", lines[2])
	}
}

func TestFormat_QuotesValuesWithSpaces(t *testing.T) {
	secrets := map[string]string{"MSG": "hello world"}
	out := Format(secrets, FormatOptions{})
	if !strings.Contains(out, `MSG="hello world"`) {
		t.Errorf("expected quoted value, got: %s", out)
	}
}

func TestFormat_HeaderPrependedAsComment(t *testing.T) {
	secrets := map[string]string{"X": "y"}
	out := Format(secrets, FormatOptions{Header: "generated by vaultpull"})
	if !strings.HasPrefix(out, "# generated by vaultpull") {
		t.Errorf("expected header comment, got: %s", out)
	}
}
